name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t atc_tlsr_paper .

    - name: Run Firmware Build
      run: |
        mkdir -p Firmware/out
        docker run --rm -v "${{ github.workspace }}/Firmware/out:/project/Firmware/out" atc_tlsr_paper

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-firmware
        path: Firmware/out

